[variables]
NIXPACKS_NODE_VERSION = "22"

[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
cmds = [
  "npm install -g pnpm@11.9.0 --prefix /app/.npm-global",
  "/app/.npm-global/bin/pnpm --version",
  "/app/.npm-global/bin/pnpm i --frozen-lockfile"
]

[phases.build]
cmds = ["/app/.npm-global/bin/pnpm run build"]

[start]
cmd = "/app/.npm-global/bin/pnpm run start"
